### PR TITLE
Update README.md

### LINKED ISSUE #525: Windows compilation using MSVS does not seem to work
Using the cmake approach with MSVC 2022 Community Edition and the desktop c++ workload installed:
```
PS D:\temp\cmark> mkdir build
PS D:\temp\cmark> cd build
PS D:\temp\cmark\build> cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30151.0
-- The CXX compiler identification is MSVC 19.29.30151.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Found Python3: C:/Program Files/Python39/python.exe (found version "3.9.11") found components: Interpreter
-- Configuring done
-- Generating done
-- Build files have been written to: D:/temp/cmark/build
PS D:\temp\cmark\build> make
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Using the `nmake` command:

```
PS D:\temp\cmark> nmake

Microsoft (R) Program Maintenance Utility Version 14.38.33134.0
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(3) : fatal error U1001: syntax error : illegal character '?' in macro
Stop.
PS D:\temp\cmark>
```

### PR DESCRIPTION
**Pull request by Pomax**
Fixes #525

### CODE REVIEW

**Comment by Pomax** [comment]
Note that this PR does not delete `nmake.bat`, but PowerShell can't run that so it might make sense to remove that.

**Comment by jgm** [comment]
Thanks!

**Comment by Pomax** [comment]
@jgm would you like me to make a PR that removes the `nmake.bat` as well? (with a separate issue filed of course so the PR can be linked to that)

**Comment by jgm** [comment]
I really don't know enough about Windows building to judge. I didn't put it there, and I'm not sure what purpose it serves!

**Comment by Pomax** [comment]
As a "I have to use every OS on the daily" person: fair enough! In that case I'll file a PR to remove it, since it doesn't actually help make the compile work =)

**Pull request merged**
