### PR TITLE
fuzz: Test more parser entry points

### PR DESCRIPTION
**Pull request by nwellnhof**
Use the upper bits of 'options' to select a parser mode from

- cmark_parse_document
- cmark_parse_file
- cmark_parser_new/feed/finish
- cmark_markdown_to_html

### CODE REVIEW

**Comment by jgm** [comment]
CIFuzz is failing after this.  Do you want me to merge it anyway?

**Comment by nwellnhof** [comment]
It turned out that the libFuzzer Makefile target didn't enable ASan. I force pushed some fixes.

`posix (macos, clang, shared)` now failed because of a timeout. This seems unrelated.

**Comment by nwellnhof** [comment]
I force-pushed again and all tests are green.

**Comment by nwellnhof** [comment]
OSS-Fuzz coverage is now at 96%: https://storage.googleapis.com/oss-fuzz-coverage/cmark/reports/20240402/linux/src/cmark/src/report.html

My plan is to add a fuzzer for the uncovered tree API functions similar to work I recently completed on libxml2: https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/fuzz/api.c?ref_type=heads. But this might take a while.

**Pull request merged**
