### PR TITLE
Generate export header for static-only build

### PR DESCRIPTION
**Pull request by nwellnhof**
Fixes issue #247.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks!

**Comment by kivikakk** [comment]
We may want to consider adding CI checks that building static/shared/static+shared works and links in all cases.

**Comment by jgm** [comment]
Good idea.  Do you want to submit a PR?

+++ Ashe Connor [Nov 16 17 00:16 ]:
>   We may want to consider adding CI checks that building
>   static/shared/static+shared works and links in all cases.

**Comment by nwellnhof** [comment]
> Good idea. Do you want to submit a PR?

PR #250 adds a Travis test for building with CMARK_SHARED=OFF.

**Comment by jgm** [comment]
Great, thanks!

**Pull request merged**
