### PR TITLE
README: Correct link to travis-ci

### PR DESCRIPTION
**Pull request by mohitsinghs**

### CODE REVIEW

**Comment by kivikakk** [comment]
@jgm can we get this commit merged please? Currently the badge just says "unknown".

**Comment by mohitsinghs** [comment]
After 9 days, I thought this will never be merged so I closed pull request and deleted repo. Anyway there are a few more links still pointing to old repo. Thanks anyway.

**Comment by kivikakk** [comment]
@mohitsinghs Yeah, I figured that was the case. I believe jgm doesn't get all that much time to work on maintaining the repo, but he should still be able to pull in your commit at https://github.com/commonmark/cmark/pull/245/commits/3ee1225d612e411cdaecae403013d240ba29d076. Sorry this is taking so long!

**Comment by jgm** [comment]
Sorry I overlooked this.  I've made the changes manually.

**Pull request closed without merging**
